import Header from '@/components/layout/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Hero from '@/sections/Hero'
import Section from '@/sections/Section'
import Footer from '@/components/layout/Footer'
import BodySection from '@/sections/MainSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Header/>
        <Hero/>
        <Section/>
        <BodySection/>
        <Footer/>
        </body>
    </html>
  )
}
